# Generated by Django 5.2.17 on 2026-10-05 18:59

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0002_businesscategory_business_public_id_and_more'),
        ('catalog', '0003_product_productvariant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('low_stock_threshold', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='businesses.business')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('public_id',),
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('movement_type', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie'), ('ADJUSTMENT', 'Ajustement'), ('TRANSFER', 'Transfert'), ('SALE', 'Vente'), ('RETURN', 'Retour')], max_length=12)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantity_before', models.DecimalField(decimal_places=3, max_digits=14)),
                ('quantity_after', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('reference_type', models.CharField(blank=True, editable=False, max_length=40, null=True)),
                ('reference_id', models.CharField(blank=True, editable=False, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='businesses.business')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryitem')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='accounts.carriidentity')),
            ],
            options={
                'ordering': ('-created_at', '-public_id'),
            },
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('variant__isnull', True)), models.Q(('product__isnull', True), ('variant__isnull', False)), _connector='OR'), name='inventory_item_exactly_one_sellable'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('product',), name='inventory_item_unique_product'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('variant',), name='inventory_item_unique_variant'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventory_item_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='inventory_item_reserved_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='inventory_item_reserved_lte_quantity'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('low_stock_threshold__isnull', True), ('low_stock_threshold__gte', 0), _connector='OR'), name='inventory_item_threshold_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_before__gte', 0)), name='stock_movement_before_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_after__gte', 0)), name='stock_movement_after_nonnegative'),
        ),
    ]
