# Generated by Django 5.2.17 on 2026-10-06 12:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Virement bancaire'), ('CARD', 'Carte'), ('OTHER', 'Autre')], max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255)),
                ('idempotency_fingerprint', models.CharField(blank=True, max_length=64)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='accounts.carriidentity')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchases.purchase')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_supplier_payments', to='accounts.carriidentity')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='supplier_payment_amount_positive'), models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('purchase', 'idempotency_key'), name='supplier_payment_idempotency_key')],
            },
        ),
    ]
