# Generated by Django 5.2.17 on 2026-10-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0002_businesscategory_business_public_id_and_more'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_positive'),
        ),
    ]
