# Generated by Django 5.2.17 on 2026-10-06 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0002_businesscategory_business_public_id_and_more'),
        ('expenses', '0004_alter_expense_payment_method'),
        ('receivables', '0002_alter_receivablepayment_payment_method_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('direction', models.CharField(choices=[('INFLOW', 'Inflow'), ('OUTFLOW', 'Outflow')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], max_length=3)),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Virement bancaire'), ('CARD', 'Carte'), ('OTHER', 'Autre')], max_length=20)),
                ('event_type', models.CharField(choices=[('SALE_PAYMENT', 'Sale payment'), ('RECEIVABLE_PAYMENT', 'Receivable payment'), ('EXPENSE_PAYMENT', 'Expense payment'), ('EXPENSE_REVERSAL', 'Expense reversal')], max_length=24)),
                ('occurred_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('idempotency_key', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='businesses.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.carriidentity')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.expense')),
                ('receivable_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='receivables.receivablepayment')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='finance.financialmovement')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.sale')),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='financial_movement_amount_positive'), models.CheckConstraint(condition=models.Q(models.Q(('expense__isnull', True), ('receivable_payment__isnull', True), ('reversal_of__isnull', False), ('sale__isnull', True)), models.Q(('reversal_of__isnull', True), models.Q(models.Q(('expense__isnull', True), ('receivable_payment__isnull', True), ('sale__isnull', False)), models.Q(('expense__isnull', True), ('receivable_payment__isnull', False), ('sale__isnull', True)), models.Q(('expense__isnull', False), ('receivable_payment__isnull', True), ('sale__isnull', True)), _connector='OR')), _connector='OR'), name='financial_movement_valid_source'), models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('business', 'idempotency_key'), name='financial_movement_business_idempotency_key'), models.UniqueConstraint(condition=models.Q(('sale__isnull', False)), fields=('sale', 'event_type'), name='financial_movement_sale_event_unique'), models.UniqueConstraint(condition=models.Q(('expense__isnull', False)), fields=('expense', 'event_type'), name='financial_movement_expense_event_unique')],
            },
        ),
    ]
