# Generated by Django 5.2.17 on 2026-10-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_financialmovement_financial_movement_valid_source_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='financialmovement',
            name='financial_movement_valid_source',
        ),
    ]
