# Generated by Django 5.2.17 on 2026-10-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0002_businesscategory_business_public_id_and_more'),
        ('expenses', '0005_expensepayment'),
        ('finance', '0004_financialmovement_supplier_payment_and_more'),
        ('purchases', '0002_supplierpayment'),
        ('receivables', '0003_receivablepayment_idempotency_fingerprint_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='financialmovement',
            name='financial_movement_valid_source',
        ),
        migrations.AddConstraint(
            model_name='financialmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('expense__isnull', True), ('expense_payment__isnull', True), ('receivable_payment__isnull', True), ('reversal_of__isnull', False), ('sale__isnull', True), ('supplier_payment__isnull', True)), models.Q(('reversal_of__isnull', True), models.Q(models.Q(('expense__isnull', True), ('expense_payment__isnull', True), ('receivable_payment__isnull', True), ('sale__isnull', False), ('supplier_payment__isnull', True)), models.Q(('expense__isnull', True), ('expense_payment__isnull', True), ('receivable_payment__isnull', False), ('sale__isnull', True), ('supplier_payment__isnull', True)), models.Q(('expense__isnull', False), ('expense_payment__isnull', True), ('receivable_payment__isnull', True), ('sale__isnull', True), ('supplier_payment__isnull', True)), models.Q(('expense__isnull', True), ('expense_payment__isnull', False), ('receivable_payment__isnull', True), ('sale__isnull', True), ('supplier_payment__isnull', True)), models.Q(('expense__isnull', True), ('expense_payment__isnull', True), ('receivable_payment__isnull', True), ('sale__isnull', True), ('supplier_payment__isnull', False)), _connector='OR')), _connector='OR'), name='financial_movement_valid_source'),
        ),
    ]
