# Generated by Django 5.2.17 on 2026-10-06 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0003_businesspaymentmethod'),
        ('finance', '0005_remove_financialmovement_financial_movement_valid_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('method_name_snapshot', models.CharField(max_length=120)),
                ('category_snapshot', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Virement bancaire'), ('CARD', 'Carte'), ('OTHER', 'Autre')], max_length=20)),
                ('recording_mode', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], max_length=10)),
                ('transaction_reference', models.CharField(blank=True, max_length=120)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='businesses.business')),
                ('business_payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='businesses.businesspaymentmethod')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.carriidentity')),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='payment_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_movement', to='finance.paymenttransaction'),
        ),
    ]
