# Generated by Django 5.2.17 on 2026-10-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0004_default_payment_methods'),
        ('expenses', '0005_expensepayment'),
        ('finance', '0006_paymenttransaction_and_more'),
        ('purchases', '0002_supplierpayment'),
        ('receivables', '0005_receivableadjustment_sale_return_and_more'),
        ('sales', '0002_salereturn_salereturnline_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='financialmovement',
            name='financial_movement_valid_source',
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='sale_return',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund_financial_movement', to='sales.salereturn'),
        ),
        migrations.AlterField(
            model_name='financialmovement',
            name='event_type',
            field=models.CharField(choices=[('SALE_PAYMENT', 'Sale payment'), ('SALE_RETURN_REFUND', 'Sale return refund'), ('RECEIVABLE_PAYMENT', 'Receivable payment'), ('EXPENSE_PAYMENT', 'Expense payment'), ('EXPENSE_REVERSAL', 'Expense reversal'), ('SUPPLIER_PAYMENT', 'Supplier payment'), ('SUPPLIER_PAYMENT_REVERSAL', 'Supplier payment reversal')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='financialmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('expense__isnull', True), ('expense_payment__isnull', True), ('receivable_payment__isnull', True), ('reversal_of__isnull', False), ('sale__isnull', True), ('sale_return__isnull', True), ('supplier_payment__isnull', True)), models.Q(('reversal_of__isnull', True), models.Q(models.Q(('expense__isnull', True), ('expense_payment__isnull', True), ('receivable_payment__isnull', True), ('sale__isnull', False), ('sale_return__isnull', True), ('supplier_payment__isnull', True)), models.Q(('expense__isnull', True), ('expense_payment__isnull', True), ('receivable_payment__isnull', True), ('sale__isnull', True), ('sale_return__isnull', False), ('supplier_payment__isnull', True)), models.Q(('expense__isnull', True), ('expense_payment__isnull', True), ('receivable_payment__isnull', False), ('sale__isnull', True), ('sale_return__isnull', True), ('supplier_payment__isnull', True)), models.Q(('expense__isnull', False), ('expense_payment__isnull', True), ('receivable_payment__isnull', True), ('sale__isnull', True), ('sale_return__isnull', True), ('supplier_payment__isnull', True)), models.Q(('expense__isnull', True), ('expense_payment__isnull', False), ('receivable_payment__isnull', True), ('sale__isnull', True), ('sale_return__isnull', True), ('supplier_payment__isnull', True)), models.Q(('expense__isnull', True), ('expense_payment__isnull', True), ('receivable_payment__isnull', True), ('sale__isnull', True), ('sale_return__isnull', True), ('supplier_payment__isnull', False)), _connector='OR')), _connector='OR'), name='financial_movement_valid_source'),
        ),
    ]
