# Generated by Django 5.2.17 on 2026-10-06 07:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0002_businesscategory_business_public_id_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('currency', models.CharField(max_length=3)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid')], default='OPEN', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='businesses.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.customer')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receivable', to='sales.sale')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivablePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile money'), ('BANK_TRANSFER', 'Bank transfer'), ('CARD', 'Card'), ('OTHER', 'Other')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='businesses.business')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='receivables.receivable')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.carriidentity')),
            ],
        ),
    ]
