# Generated by Django 5.2.17 on 2026-10-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0002_businesscategory_business_public_id_and_more'),
        ('receivables', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivablepayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Virement bancaire'), ('CARD', 'Carte'), ('OTHER', 'Autre')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='receivable',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gt', 0)), name='receivable_original_positive'),
        ),
        migrations.AddConstraint(
            model_name='receivablepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='receivable_payment_positive'),
        ),
    ]
