# Generated by Django 5.2.17 on 2026-10-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0002_businesscategory_business_public_id_and_more'),
        ('receivables', '0002_alter_receivablepayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivablepayment',
            name='idempotency_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='receivablepayment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='receivablepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('business', 'idempotency_key'), name='receivable_payment_business_idempotency_key'),
        ),
    ]
