# Generated by Django 5.2.17 on 2026-10-07 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0004_default_payment_methods'),
        ('receivables', '0003_receivablepayment_idempotency_fingerprint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivableAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('adjustment_type', models.CharField(choices=[('RETURN_CREDIT', 'Return credit')], default='RETURN_CREDIT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='businesses.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.carriidentity')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='receivables.receivable')),
            ],
        ),
    ]
