# Generated by Django 5.2.17 on 2026-10-07 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0004_receivableadjustment'),
        ('sales', '0002_salereturn_salereturnline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivableadjustment',
            name='sale_return',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receivable_adjustment', to='sales.salereturn'),
        ),
        migrations.AddConstraint(
            model_name='receivableadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='receivable_adjustment_positive'),
        ),
    ]
