# Generated by Django 5.2.17 on 2026-10-05 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


def _seed_categories(apps):
    """Provide a small, idempotent taxonomy useful on a new installation."""
    ProductCategory = apps.get_model("catalog", "ProductCategory")
    roots = {
        "ELECTRONICS": ("Électronique", "electronics", 10),
        "FASHION": ("Mode", "fashion", 20),
        "FOOD": ("Alimentation", "food", 30),
    }
    root_objects = {}
    for code, (name, slug, sort_order) in roots.items():
        root_objects[code], _ = ProductCategory.objects.get_or_create(
            code=code,
            defaults={"name": name, "slug": slug, "sort_order": sort_order},
        )
    categories = (
        ("PHONES", "Téléphones", "phones", "ELECTRONICS", None, 10),
        ("SMARTPHONES", "Smartphones", "smartphones", "PHONES", "SMARTPHONE", 10),
        ("SHOES", "Chaussures", "shoes", "FASHION", "SHOES", 10),
        ("DRINKS", "Boissons", "drinks", "FOOD", "DRINK", 10),
    )
    for code, name, slug, parent_code, product_type_key, sort_order in categories:
        ProductCategory.objects.get_or_create(
            code=code,
            defaults={
                "name": name,
                "slug": slug,
                "parent": root_objects.get(parent_code)
                or ProductCategory.objects.get(code=parent_code),
                "product_type_key": product_type_key,
                "sort_order": sort_order,
            },
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('product_type_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.productcategory')),
            ],
            options={
                'ordering': ('sort_order', 'name', 'code'),
            },
        ),
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=160)),
                ('data_type', models.CharField(choices=[('text', 'Texte'), ('integer', 'Entier'), ('decimal', 'Décimal'), ('boolean', 'Booléen'), ('choice', 'Choix'), ('date', 'Date')], max_length=16)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('is_required', models.BooleanField(default=False)),
                ('is_filterable', models.BooleanField(default=False)),
                ('is_variant_axis', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='catalog.productcategory')),
            ],
            options={
                'ordering': ('sort_order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=128)),
                ('label', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='catalog.attributedefinition')),
            ],
            options={
                'ordering': ('sort_order', 'label', 'value'),
                'constraints': [models.UniqueConstraint(fields=('attribute_definition', 'value'), name='catalog_option_definition_value_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='attributedefinition',
            constraint=models.UniqueConstraint(fields=('category', 'code'), name='catalog_attribute_category_code_unique'),
        ),
    ]
