# Generated by Django 5.2.17 on 2026-10-05 18:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_businesscategory_business_public_id_and_more'),
        ('catalog', '0002_seed_demo_taxonomy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('internal_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=128, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], max_length=3)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='businesses.business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productcategory')),
            ],
            options={
                'ordering': ('name', 'public_id'),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('internal_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.CharField(blank=True, max_length=128, null=True)),
                ('attributes', models.JSONField(default=dict)),
                ('variant_signature', models.CharField(editable=False, max_length=64)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.product')),
            ],
            options={
                'ordering': ('public_id',),
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_reference__isnull', False)), fields=('business', 'internal_reference'), name='catalog_product_business_internal_reference_unique'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='catalog_product_selling_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__isnull', True), ('cost_price__gte', 0), _connector='OR'), name='catalog_product_cost_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'variant_signature'), name='catalog_variant_product_signature_unique'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_reference__isnull', False)), fields=('product', 'internal_reference'), name='catalog_variant_product_internal_reference_unique'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__isnull', True), ('selling_price__gte', 0), _connector='OR'), name='catalog_variant_selling_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__isnull', True), ('cost_price__gte', 0), _connector='OR'), name='catalog_variant_cost_price_nonnegative'),
        ),
    ]
