# Generated by Django 5.2.17 on 2026-10-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carriidentity',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='carriidentity',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carriidentity',
            name='last_oidc_auth_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carriidentity',
            name='verified_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
    ]
