# Generated by Django 5.2.17 on 2026-10-10 11:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, editable=False, help_text='Reference publique unique du client applicatif, format AC + 10 caracteres.', max_length=12, unique=True, verbose_name='reference')),
                ('name', models.CharField(help_text='Nom humain du client applicatif, par exemple Ecommerce Web.', max_length=150, verbose_name='nom')),
                ('client_id', models.CharField(db_index=True, help_text='Identifiant technique stable envoye dans X-Ecommerce-Client-Id.', max_length=80, unique=True, validators=[django.core.validators.RegexValidator(message='Le client_id doit contenir uniquement des lettres minuscules, des chiffres, des tirets ou des underscores, sans separateur aux extremites.', regex='^[a-z0-9][a-z0-9_-]*[a-z0-9]$|^[a-z0-9]$')], verbose_name='client_id')),
                ('client_type', models.CharField(choices=[('WEB', 'Web'), ('MOBILE_ANDROID', 'Mobile Android'), ('MOBILE_IOS', 'Mobile iOS'), ('DESKTOP', 'Desktop'), ('PARTNER', 'Partner'), ('INTERNAL_SERVICE', 'Service interne'), ('WORKER', 'Worker'), ('OTHER', 'Autre')], default='OTHER', help_text='Famille applicative du client consommateur.', max_length=40, verbose_name='type de client')),
                ('auth_method', models.CharField(choices=[('HMAC', 'HMAC'), ('PLAY_INTEGRITY', 'Play Integrity'), ('APP_ATTEST', 'App Attest'), ('PUBLIC_KEY', 'Cle publique'), ('OAUTH_CLIENT_CREDENTIALS', 'OAuth Client Credentials'), ('MTLS', 'mTLS'), ('NONE', 'Aucune'), ('OTHER', 'Autre')], default='HMAC', help_text='Methode attendue pour authentifier ce client.', max_length=40, verbose_name="methode d'authentification")),
                ('is_active', models.BooleanField(default=True, help_text='Permet de revoquer un client sans supprimer son historique.', verbose_name='actif')),
                ('description', models.TextField(blank=True, default='', help_text="Informations non sensibles sur l'usage du client.", verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadonnees non sensibles reservees aux futurs besoins.', verbose_name='metadata')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Derniere authentification client reussie.', null=True, verbose_name='derniere utilisation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de derniere modification')),
            ],
            options={
                'verbose_name': 'client applicatif API',
                'verbose_name_plural': 'clients applicatifs API',
                'ordering': ['name', 'client_id'],
                'indexes': [models.Index(fields=['client_id'], name='api_client_client_id_idx'), models.Index(fields=['is_active', 'auth_method'], name='api_client_auth_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientNonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nonce', models.CharField(max_length=128)),
                ('seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonces', to='api_clients.apiclient')),
            ],
            options={
                'verbose_name': 'nonce client',
                'verbose_name_plural': 'nonces clients',
                'ordering': ['-seen_at'],
                'constraints': [models.UniqueConstraint(fields=('client', 'nonce'), name='unique_client_nonce')],
            },
        ),
    ]
