# Generated by Django 5.2.17 on 2026-10-07 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0004_default_payment_methods'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('POSTED', 'Posted')], default='POSTED', max_length=12)),
                ('reason', models.TextField(blank=True)),
                ('returned_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=255)),
                ('idempotency_fingerprint', models.CharField(max_length=64)),
                ('receivable_credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='businesses.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.carriidentity')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.customer')),
                ('refund_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='businesses.businesspaymentmethod')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale')),
            ],
            options={
                'ordering': ('-returned_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SaleReturnLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_cost_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='sales.saleline')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='sales.salereturn')),
            ],
        ),
        migrations.AddConstraint(
            model_name='salereturn',
            constraint=models.CheckConstraint(condition=models.Q(('receivable_credit_amount__gte', 0), ('refund_amount__gte', 0)), name='sale_return_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='salereturn',
            constraint=models.UniqueConstraint(fields=('business', 'idempotency_key'), name='sale_return_business_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='salereturnline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sale_return_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='salereturnline',
            constraint=models.UniqueConstraint(fields=('sale_return', 'sale_line'), name='sale_return_one_line_per_sale_line'),
        ),
    ]
