# Generated by Django 5.2.17 on 2026-10-05 17:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('zone', models.CharField(blank=True, max_length=120)),
                ('primary_currency', models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='CDF', max_length=3)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='businesses.business')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_memberships', to='accounts.carriidentity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('identity', 'business'), name='unique_business_identity')],
            },
        ),
    ]
