# Generated by Django 5.2.17 on 2026-10-06 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_businesscategory_business_public_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Virement bancaire'), ('CARD', 'Carte'), ('OTHER', 'Autre')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='businesses.business')),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('business', 'name'), name='business_payment_method_unique_name')],
            },
        ),
    ]
