# Generated by Django 5.2.17 on 2026-10-08 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_default_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmember',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessmember',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='businessmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=10),
        ),
        migrations.CreateModel(
            name='BusinessMemberPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('VIEW_MEMBERS', 'View members'), ('MANAGE_MEMBERS', 'Manage members'), ('UPDATE_BUSINESS', 'Update business'), ('MANAGE_PAYMENT_METHODS', 'Manage payment methods'), ('VIEW_CATALOG', 'View catalog'), ('MANAGE_CATALOG', 'Manage catalog'), ('VIEW_INVENTORY', 'View inventory'), ('MANAGE_EXPENSE_CATEGORIES', 'Manage expense categories'), ('CREATE_EXPENSES', 'Create expenses'), ('VIEW_EXPENSES', 'View expenses'), ('MANAGE_EXPENSES', 'Manage expenses'), ('VIEW_PURCHASES', 'View purchases'), ('MANAGE_PURCHASES', 'Manage purchases'), ('USE_POS', 'Use point of sale'), ('MANAGE_SALES', 'Manage sales'), ('MANAGE_SALE_RETURNS', 'Manage sale returns'), ('VIEW_RECEIVABLES', 'View receivables'), ('MANAGE_RECEIVABLES', 'Manage receivables'), ('VIEW_FINANCIAL_SUMMARY', 'View financial summary'), ('MANAGE_INVENTORY', 'Manage inventory'), ('VIEW_DASHBOARD', 'View dashboard'), ('VIEW_PROFITABILITY', 'View profitability'), ('VIEW_REPORTS', 'View reports')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='businesses.businessmember')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('member', 'permission'), name='unique_member_permission')],
            },
        ),
    ]
