# Generated by Django 5.2.17 on 2026-10-08 09:46

from django.db import migrations, models


def backfill_is_owner_and_title(apps, schema_editor):
    BusinessMember = apps.get_model("businesses", "BusinessMember")
    duplicate_owner = (
        BusinessMember.objects.filter(role="OWNER")
        .values("business_id")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
        .order_by("business_id")
        .first()
    )
    if duplicate_owner:
        raise RuntimeError(
            "Cannot migrate a Business with multiple legacy OWNER memberships: "
            f"{duplicate_owner['business_id']}."
        )

    for member in BusinessMember.objects.all():
        if member.role == "OWNER":
            member.is_owner = True
            member.title = "Gérant"
        elif member.role == "MANAGER":
            member.is_owner = False
            member.title = "Gestionnaire"
        else:
            member.is_owner = False
            member.title = "Employé"
        member.save()


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0005_add_member_title_owner_and_permissions"),
    ]

    operations = [
        migrations.RunPython(backfill_is_owner_and_title, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="businessmember",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_owner", True)),
                fields=("business",),
                name="unique_business_owner",
            ),
        ),
    ]
