# Generated by Django 5.2.17 on 2026-10-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_backfill_member_title_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmemberpermission',
            name='permission',
            field=models.CharField(choices=[('VIEW_MEMBERS', 'View members'), ('MANAGE_MEMBERS', 'Manage members'), ('UPDATE_BUSINESS', 'Update business'), ('VIEW_PAYMENT_METHODS', 'View payment methods'), ('MANAGE_PAYMENT_METHODS', 'Manage payment methods'), ('VIEW_CUSTOMERS', 'View customers'), ('MANAGE_CUSTOMERS', 'Manage customers'), ('VIEW_CATALOG', 'View catalog'), ('MANAGE_CATALOG', 'Manage catalog'), ('VIEW_INVENTORY', 'View inventory'), ('MANAGE_EXPENSE_CATEGORIES', 'Manage expense categories'), ('CREATE_EXPENSES', 'Create expenses'), ('VIEW_EXPENSES', 'View expenses'), ('MANAGE_EXPENSES', 'Manage expenses'), ('VIEW_PURCHASES', 'View purchases'), ('MANAGE_PURCHASES', 'Manage purchases'), ('USE_POS', 'Use point of sale'), ('VIEW_SALES', 'View sales'), ('MANAGE_SALES', 'Manage sales'), ('MANAGE_SALE_RETURNS', 'Manage sale returns'), ('VIEW_RECEIVABLES', 'View receivables'), ('MANAGE_RECEIVABLES', 'Manage receivables'), ('VIEW_FINANCIAL_SUMMARY', 'View financial summary'), ('MANAGE_INVENTORY', 'Manage inventory'), ('VIEW_DASHBOARD', 'View dashboard'), ('VIEW_PROFITABILITY', 'View profitability'), ('VIEW_REPORTS', 'View reports')], max_length=40),
        ),
    ]
