# Generated by Django 5.2.17 on 2026-10-09 11:13

import secrets

import django.db.models.deletion
from django.db import migrations, models


ALPHABET = "23456789ABCDEFGHJKLMNPQRSTUVWXYZ"


def backfill_member_public_ids(apps, schema_editor):
    """Allocate distinct opaque identifiers to memberships created before P1-A4."""
    BusinessMember = apps.get_model("businesses", "BusinessMember")
    existing = set(
        BusinessMember.objects.exclude(public_id__isnull=True).values_list(
            "public_id",
            flat=True,
        )
    )
    for member in BusinessMember.objects.filter(public_id__isnull=True).iterator():
        while True:
            candidate = "BM" + "".join(
                secrets.choice(ALPHABET) for _ in range(10)
            )
            if candidate not in existing:
                break
        BusinessMember.objects.filter(pk=member.pk).update(public_id=candidate)
        existing.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0007_alter_businessmemberpermission_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessmember",
            name="public_id",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=12,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="businessmember",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessmember",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="business_members_removed",
                to="accounts.carriidentity",
            ),
        ),
        migrations.AddField(
            model_name="businessmember",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessmember",
            name="suspended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="business_members_suspended",
                to="accounts.carriidentity",
            ),
        ),
        migrations.AlterField(
            model_name="businessmember",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("SUSPENDED", "Suspended"),
                    ("REMOVED", "Removed"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
        migrations.RunPython(
            backfill_member_public_ids,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="businessmember",
            name="public_id",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
    ]
