# Generated by Django 5.2.17 on 2026-10-09 14:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('businesses', '0008_member_public_id_and_logical_removal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessMemberInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, editable=False, max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('normalized_email', models.EmailField(db_index=True, max_length=254)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=10)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('resend_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_member_invitations_accepted', to='accounts.carriidentity')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_invitations', to='businesses.business')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_member_invitations_sent', to='accounts.carriidentity')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_member_invitations', to='businesses.businessmember')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['business', 'status', 'created_at'], name='biz_member_invitation_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('business', 'normalized_email'), name='unique_pending_business_member_invitation'), models.UniqueConstraint(condition=models.Q(('status', 'EXPIRED')), fields=('business', 'normalized_email'), name='unique_expired_business_member_invitation')],
            },
        ),
    ]
