# Generated by Django 5.2.17 on 2026-10-10 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_carriidentity_email_verified_and_more'),
        ('businesses', '0009_businessmemberinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmemberinvitation',
            name='declined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_member_invitations_declined', to='accounts.carriidentity'),
        ),
    ]
